[package]
name = "lib"
version.workspace = true
edition.workspace = true

[lib]
name = "lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger.workspace = true
pyo3-stub-gen.workspace = true
pyo3.workspace = true
tokio.workspace = true

[[bin]]
name = "stub_gen"
doc = false
